### ISSUE TITLE
Accumulateurs de métrique pas reset par joueur

### ISSUE THREAD

**Issue by dalloriam** [TSAP-Laval/consume-backend#14]
https://github.com/TSAP-Laval/consume-backend/blob/master/stats/teamStats.go#L37

Les accumulateurs de métrique sont définis à l'extérieur de la loop de joueurs, donc la moyenne ne repart pas à 0 pour chaque joueur, causant une accumulation de joueur en joueur

**Comment by loicndjoyi** [comment]
Est maintenant fonctionnelle en production.
